// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";

import {MockUSDC} from "../../src/MockUSDC.sol";
import {ComplianceRegistry} from "../../src/ComplianceRegistry.sol";
import {TBillToken} from "../../src/TBillToken.sol";
import {TBillVault} from "../../src/TBillVault.sol";
import {MockPriceFeed} from "../../src/exercises/MockPriceFeed.sol";
import {MockTBillCustodian} from "../../src/exercises/MockTBillCustodian.sol";
import {RedemptionQueue} from "../../src/exercises/RedemptionQueue.sol";

/// @title Ex5 — the redemption queue: four TODOs in src/exercises/RedemptionQueue.sol
/// @notice These tests are your acceptance criteria, not your task. They are red because the
///         four functions in RedemptionQueue.sol are still stubs that revert. Implement them,
///         and this file goes green. Do not edit this file.
///
///         Acceptance: make exercise (it should be red until you are finished)
///
/// @dev The whole exercise turns on one conversion. Three decimal scales:
///        shares  18 decimals   (tBILL)
///        NAV      8 decimals   (per share)
///        assets   6 decimals   (USDC)        18 + 8 - 6 = 20
contract QueueTasksTest is Test {
    MockUSDC internal usdc;
    ComplianceRegistry internal compliance;
    MockPriceFeed internal feed;
    TBillToken internal tBill;
    MockTBillCustodian internal custodian;
    TBillVault internal vault;
    RedemptionQueue internal queue;

    address internal admin = address(this);
    address internal alice = makeAddr("alice");
    address internal bob = makeAddr("bob");

    uint256 internal constant AMOUNT = 1_000e6;
    uint256 internal constant PAR = 1e8;
    uint256 internal constant NAV_1_25 = 1.25e8;

    function setUp() public {
        usdc = new MockUSDC();
        compliance = new ComplianceRegistry(admin);
        feed = new MockPriceFeed(int256(PAR));
        tBill = new TBillToken(admin, compliance);
        custodian = new MockTBillCustodian(admin);
        vault = new TBillVault(usdc, tBill, feed, custodian, admin);
        queue = new RedemptionQueue(vault, tBill, usdc, admin);

        // Wiring — the part you must not skip. The queue needs MINTER_ROLE to burn the shares
        // it holds, and it must be whitelisted because burning counts as a balance change.
        tBill.grantRole(tBill.MINTER_ROLE(), address(vault));
        tBill.grantRole(tBill.MINTER_ROLE(), address(queue));
        custodian.grantRole(custodian.CUSTODIAN_ROLE(), address(vault));
        vault.setQueue(address(queue));

        compliance.setWhitelisted(admin, true);
        compliance.setWhitelisted(alice, true);
        compliance.setWhitelisted(bob, true);
        compliance.setWhitelisted(address(queue), true);
    }

    function _subscribe(address user, uint256 assets) internal {
        usdc.faucet(user, assets);
        vm.startPrank(user);
        usdc.approve(address(vault), assets);
        vault.subscribe(assets);
        vm.stopPrank();
    }

    function _enqueue(address user, uint256 shares) internal returns (uint256 id) {
        vm.startPrank(user);
        tBill.approve(address(queue), shares);
        id = queue.enqueue(shares);
        vm.stopPrank();
    }

    /// @dev Give the vault cash the way the SPV would, so a settlement can draw on it
    function _fundVault(uint256 assets) internal {
        usdc.faucet(admin, assets);
        usdc.approve(address(vault), assets);
        vault.depositReserves(assets);
    }

    // ==================================================================
    // Ex5.1 — the decimal conversion
    // ==================================================================

    /// @dev At par, 1000e18 shares are worth exactly 1000e6 USDC
    function test_Ex5_1_AssetsAtNav_AtPar() public view {
        assertEq(queue.assetsAtNav(1_000e18, PAR), 1_000e6, "1000 shares at NAV 1.00 = 1000 USDC");
    }

    /// @dev When the NAV rises to 1.25, the SAME 1000 shares are worth 1250 USDC, and only
    ///      800 shares are worth 1000. Get the 10^20 right or this is off by 10^12.
    function test_Ex5_1_AssetsAtNav_AtHigherNav() public view {
        assertEq(queue.assetsAtNav(1_000e18, NAV_1_25), 1_250e6, "1000 shares at 1.25 = 1250");
        assertEq(queue.assetsAtNav(800e18, NAV_1_25), 1_000e6, "800 shares at 1.25 = 1000");
    }

    // ==================================================================
    // Ex5.2 — enqueue: escrow the shares, lock the payout
    // ==================================================================

    function test_Ex5_2_Enqueue_EscrowsSharesAndLocksNav() public {
        _subscribe(alice, AMOUNT);
        uint256 id = _enqueue(alice, 1_000e18);

        assertEq(id, 0, "the first ticket is id 0");
        assertEq(tBill.balanceOf(alice), 0, "the shares are escrowed in the queue");
        assertEq(tBill.balanceOf(address(queue)), 1_000e18, "the queue now holds them");
        assertEq(queue.pendingShares(), 1_000e18, "and says so");
        assertEq(queue.pendingAssets(), 1_000e6, "the payout is locked at par");

        RedemptionQueue.Request memory r = queue.requestAt(0);
        assertEq(r.owner, alice);
        assertEq(r.shares, 1_000e18);
        assertEq(r.assetsLocked, 1_000e6);
        assertFalse(r.settled);
    }

    /// @dev The rate is fixed when you join the queue. A later NAV move changes what the
    ///      remaining holders' shares are worth, but not this ticket.
    function test_Ex5_2_Enqueue_LocksTheRate() public {
        _subscribe(alice, AMOUNT);
        _enqueue(alice, 1_000e18);

        vault.attest(int256(NAV_1_25));

        RedemptionQueue.Request memory r = queue.requestAt(0);
        assertEq(r.assetsLocked, 1_000e6, "the locked payout does not drift with the NAV");
        assertEq(
            vault.totalClaimValue(),
            1_250e6,
            "...even though the remaining shares are now worth more"
        );
    }

    // ==================================================================
    // Ex5.3 — settle: strict FIFO, all-or-nothing per ticket
    // ==================================================================

    /// @dev Two identical tickets, enough cash for both: both are paid, head moves to the end
    function test_Ex5_3_Settle_PaysTheWholeQueue() public {
        _subscribe(alice, AMOUNT);
        _subscribe(bob, AMOUNT);
        _enqueue(alice, 1_000e18);
        _enqueue(bob, 1_000e18);

        uint256 filled = queue.settle(2_000e6);

        assertEq(filled, 2_000e6, "both tickets were honoured");
        assertEq(queue.head(), 2, "the queue is empty");
        assertEq(queue.pendingShares(), 0);
        assertEq(queue.pendingAssets(), 0);
        assertEq(queue.claimable(alice), 1_000e6);
        assertEq(queue.claimable(bob), 1_000e6);
        assertEq(queue.totalClaimable(), 2_000e6);
    }

    /// @dev Cash is short: the head ticket is paid, the second waits. Never pay out of order.
    function test_Ex5_3_Settle_PartialFillCarriesTheRemainder() public {
        _subscribe(alice, AMOUNT);
        _subscribe(bob, AMOUNT);
        _enqueue(alice, 1_000e18);
        _enqueue(bob, 1_000e18);

        uint256 filled = queue.settle(1_500e6);

        assertEq(filled, 1_000e6, "only the head ticket could be honoured in full");
        assertEq(queue.head(), 1, "head advanced past alice only");
        assertEq(queue.claimable(alice), 1_000e6);
        assertEq(queue.claimable(bob), 0, "bob is still waiting");
        assertEq(queue.pendingAssets(), 1_000e6, "bob's payout is still owed");
        assertEq(queue.pendingShares(), 1_000e18, "and his shares are still escrowed");
        assertEq(tBill.balanceOf(address(queue)), 1_000e18);
    }

    /// @dev Not enough cash for even the head ticket: nothing is paid, head does not move
    function test_Ex5_3_Settle_StopsWhenItCannotCoverTheHead() public {
        _subscribe(alice, AMOUNT);
        _enqueue(alice, 1_000e18);

        uint256 filled = queue.settle(500e6);

        assertEq(filled, 0, "a ticket is all-or-nothing: no partial payout");
        assertEq(queue.head(), 0, "the head ticket is untouched");
        assertEq(queue.pendingAssets(), 1_000e6);
        assertEq(queue.claimable(alice), 0);
    }

    /// @dev The T+1 story end to end: the cash was invested, the vault is empty, so a
    ///      settlement cannot draw on it until the SPV wires the proceeds back
    function test_Ex5_3_Settle_NeedsTheVaultToHoldCash() public {
        _subscribe(alice, AMOUNT);
        vault.invest(AMOUNT); // cash out to the custodian, buffer to zero
        _enqueue(alice, 1_000e18);

        assertEq(vault.reserveBalance(), 0, "the buffer is fully invested");
        vm.expectRevert(TBillVault.InsufficientReserves.selector);
        queue.settle(1_000e6);

        _fundVault(AMOUNT); // T+1: the SPV sells T-Bills and wires the cash back
        assertEq(queue.settle(1_000e6), 1_000e6, "now the settlement can be honoured");
        assertEq(queue.claimable(alice), 1_000e6);
    }

    // ==================================================================
    // Ex5.4 — claim: collect a settled ticket
    // ==================================================================

    function test_Ex5_4_Claim_PaysOutAndZeroesTheBalance() public {
        _subscribe(alice, AMOUNT);
        _enqueue(alice, 1_000e18);
        queue.settle(1_000e6);

        uint256 before = usdc.balanceOf(alice);
        vm.prank(alice);
        uint256 paid = queue.claim();

        assertEq(paid, 1_000e6);
        assertEq(usdc.balanceOf(alice), before + 1_000e6, "alice is paid in USDC");
        assertEq(queue.claimable(alice), 0, "the claim is zeroed before the transfer");
        assertEq(queue.totalClaimable(), 0);
        assertEq(usdc.balanceOf(address(queue)), 0, "the queue holds nothing it does not owe");
    }

    function test_Ex5_4_Claim_RevertsWithNothingToClaim() public {
        vm.expectRevert(RedemptionQueue.NothingToClaim.selector);
        vm.prank(alice);
        queue.claim();
    }

    /// @dev Two settlements against the same ticket must not pay twice — the CEI check
    function test_Ex5_4_Claim_CannotBeDrawnTwice() public {
        _subscribe(alice, AMOUNT);
        _enqueue(alice, 1_000e18);
        queue.settle(1_000e6);

        vm.startPrank(alice);
        queue.claim();
        vm.expectRevert(RedemptionQueue.NothingToClaim.selector);
        queue.claim();
        vm.stopPrank();
    }
}
